repositories:
  - name: llm-d-modelservice
    url: https://llm-d-incubation.github.io/llm-d-modelservice/

releases:
  - name: infra-inference-scheduling
    chart: https://llm-d-incubation.github.io/llm-d-infra/
    version: v1.1.0
    installed: true
    labels:
      managedBy: llm-d-infra-installer

  - name: gaie-inference-scheduling
    chart: oci://registry.k8s.io/gateway-api-inference-extension/charts/inferencepool
    version: v0.5.1
    installed: true
    needs:
      - infra-inference-scheduling
    values:
      - gaie-inference-scheduling/values.yaml
    setString:
      - name: provider.name
        value: gke
    labels:
      managedBy: helmfile

  - name: ms-inference-scheduling
    chart: llm-d-modelservice/llm-d-modelservice
    version: v0.2.0
    installed: true
    needs:
      - infra-inference-scheduling
      - gaie-inference-scheduling
    values:
      - ms-inference-scheduling/values.yaml
    labels:
      managedBy: helmfile
    # NOTE: This is a temporary workaround.
    hooks:
      - events: [ "postsync" ]
        command: bash
        args:
          - -c
          - |
            if [ "${GATEWAY}" = "gke-l7-regional-external-managed" ]; then
              echo "Removing timeout in HTTPRoute as GKE Gateway doesn't support it..."
              kubectl patch httproute ms-inference-scheduling-llm-d-modelservice \
                -n ${NAMESPACE} \
                --type=json \
                -p='[{"op": "remove", "path": "/spec/rules/0/timeouts"}]' || echo "No timeouts found to remove"
            fi
