MD013:
  line_length: 5000
  code_block_line_length: 5000
MD004:
  style: dash
MD041:
  # Heading level
  level: 1
  # RegExp for matching title in front matter
  front_matter_title: "^\\s*title\\s*[:=]"
