multinode: false

modelArtifacts:
  uri: "hf://RedHatAI/Llama-3.3-70B-Instruct-FP8-dynamic"
  size: 100Gi
  authSecretName: "llm-d-hf-token"

routing:
  modelName: RedHatAI/Llama-3.3-70B-Instruct-FP8-dynamic
  servicePort: 8000
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: infra-pd-inference-gateway

  inferenceModel:
    create: false

  inferencePool:
    create: false
    name: gaie-pd

  httpRoute:
    create: true

  epp:
    create: false

decode:
  create: true
  replicas: 1
  containers:
  - name: "vllm"
    image: "robertgouldshaw2/vllm-nixl:nixl-oh-debug-fixed-0.3" # TODO(rob): update to llm-d image
    modelCommand: vllmServe
    args:
      - "--tensor-parallel-size"
      - "4"
      - "--block-size"
      - "128"
      - "--kv-transfer-config"
      - '{"kv_connector":"NixlConnector", "kv_role":"kv_both"}'
      - "--disable-log-requests"
      - "--disable-uvicorn-access-log"
      - "--max-model-len"
      - "32000"
    env:
      - name: VLLM_NIXL_SIDE_CHANNEL_HOST
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
    resources:
      limits:
        memory: 128Gi
        cpu: "16"
        nvidia.com/gpu: "4"
        rdma/ib: 1
      requests:
        memory: 128Gi
        cpu: "16"
        nvidia.com/gpu: "4"
        rdma/ib: 1
    mountModelVolume: true
    volumeMounts:
    - name: metrics-volume
      mountPath: /.config
    - name: shm
      mountPath: /dev/shm
    - name: torch-compile-cache
      mountPath: /.cache
  volumes:
  - name: metrics-volume
    emptyDir: {}
  - name: shm
    emptyDir:
      medium: Memory
      sizeLimit: "16Gi"
  - name: torch-compile-cache
    emptyDir: {}

prefill:
  create: true
  replicas: 4
  containers:
  - name: "vllm"
    image: "robertgouldshaw2/vllm-nixl:nixl-oh-debug-fixed-0.3" # TODO(rob): update to llm-d image
    modelCommand: vllmServe
    args:
      - "--block-size"
      - "128"
      - "--kv-transfer-config"
      - '{"kv_connector":"NixlConnector", "kv_role":"kv_both"}'
      - "--disable-log-requests"
      - "--disable-uvicorn-access-log"
      - "--max-model-len"
      - "32000"
    env:
      - name: VLLM_IS_PREFILL # TODO(rob): remove once we bump vllm version
        value: "1"
      - name: VLLM_NIXL_SIDE_CHANNEL_HOST
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
    resources:
      limits:
        memory: 32Gi
        cpu: "8"
        nvidia.com/gpu: "1"
        rdma/ib: 1
      requests:
        memory: 32Gi
        cpu: "8"
        nvidia.com/gpu: "1"
        rdma/ib: 1
    mountModelVolume: true
    volumeMounts:
    - name: metrics-volume
      mountPath: /.config
    - name: shm
      mountPath: /dev/shm
    - name: torch-compile-cache
      mountPath: /.cache
  volumes:
  - name: metrics-volume
    emptyDir: {}
  - name: shm
    emptyDir:
      medium: Memory
      sizeLimit: "16Gi"
  - name: torch-compile-cache
    emptyDir: {}
