apiVersion: v1
kind: Pod
metadata:
  name: benchmark-interactive
spec:
  containers:
    - name: benchmark-runner
      image: "docker.io/robertgouldshaw2/benchmark-pod-interactive:v0.1"
      imagePullPolicy: Always
      stdin: true
      tty: true
      resources:
        requests:
          cpu: "16"
          memory: "16Gi"
        limits:
          cpu: "16"
          memory: "16Gi"
