# Creates the resources for simulating llm-d inference
multinode: false

modelArtifacts:
  uri: "hf://random"
  size: 5Mi

routing:
  # This is the model name for the openai api request
  modelName: random
  servicePort: 8000
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: infra-sim-inference-gateway

  inferenceModel:
    create: false

  inferencePool:
    create: false
    name: gaie-sim

  httpRoute:
    create: true
    matches:
    - path:
        type: PathPrefix
        value: /v1/completions
      headers:
      - name: x-model-name
        type: Exact
        value: random
    - path:
        type: PathPrefix
        value: /v1/chat/completions
      headers:
      - name: x-model-name
        type: Exact
        value: random
    - path:
        type: PathPrefix
        value: /v1/models

  epp:
    # use GAIE instead of EPP
    create: false

decode:
  create: true
  replicas: 1
  containers:
  - name: "vllm"
    image: "ghcr.io/llm-d/llm-d-inference-sim:0.0.4"
    modelCommand: imageDefault
    ports:
      - containerPort: 5557
        protocol: TCP
    mountModelVolume: true
    volumeMounts:
    - name: metrics-volume
      mountPath: /.config
  volumes:
  - name: metrics-volume
    emptyDir: {}

prefill:
  create: true
  replicas: 1
  containers:
  - name: "vllm"
    image: "ghcr.io/llm-d/llm-d-inference-sim:0.0.4"
    modelCommand: imageDefault
    ports:
      - containerPort: 5557
        protocol: TCP
    mountModelVolume: true
    volumeMounts:
    - name: metrics-volume
      mountPath: /.config
  volumes:
  - name: metrics-volume
    emptyDir: {}
