repositories:
  - name: llm-d-modelservice
    url: https://llm-d-incubation.github.io/llm-d-modelservice/

releases:
  - name: infra-sim
    namespace: llm-d-sim
    chart: https://llm-d-incubation.github.io/llm-d-infra/
    version: v1.1.1
    installed: true
    labels:
      managedBy: llm-d-infra-installer

  - name: gaie-sim
    namespace: llm-d-sim
    chart: oci://registry.k8s.io/gateway-api-inference-extension/charts/inferencepool
    version: v0.5.1
    installed: true
    needs:
      - llm-d-sim/infra-sim
    values:
      - gaie-sim/values.yaml
    labels:
      managedBy: helmfile

  - name: ms-sim
    namespace: llm-d-sim
    chart: llm-d-modelservice/llm-d-modelservice
    version: v0.2.0
    installed: true
    needs:
      - llm-d-sim/infra-sim
      - llm-d-sim/gaie-sim
    values:
      - ms-sim/values.yaml
    labels:
      managedBy: helmfile
