repositories:
  - name: llm-d-modelservice
    url: https://llm-d-incubation.github.io/llm-d-modelservice/

releases:
  - name: infra-pd
    namespace: llm-d-pd
    chart: oci://ghcr.io/llm-d-incubation/llm-d-infra/llm-d-infra
    version: v1.1.0
    installed: true
    values:
      - infra-pd/values.yaml
    labels:
      managedBy: llm-d-infra-installer

  - name: gaie-pd
    namespace: llm-d-pd
    chart: oci://registry.k8s.io/gateway-api-inference-extension/charts/inferencepool
    version: v0.5.1
    installed: true
    needs:
      - llm-d-pd/infra-pd
    values:
      - gaie-pd/values.yaml
    labels:
      managedBy: helmfile

  - name: ms-pd
    namespace: llm-d-pd
    chart: llm-d-modelservice/llm-d-modelservice
    version: v0.2.0
    installed: true
    needs:
      - llm-d-pd/infra-pd
      - llm-d-pd/gaie-pd
    values:
      - ms-pd/values.yaml
    labels:
      managedBy: helmfile
    hooks:
      - events: [ "postsync" ]
        command: bash
        args:
          - -c
          - |
            echo "Patching HTTPRoute to trigger reconciliation..."
            kubectl patch httproute ms-pd-llm-d-modelservice \
              -n llm-d-pd \
              -p '{"metadata":{"labels":{"inferencepool":"gaie-pd"}}}' \
              --type=merge
      # NOTE: This is a temporary workaround.
      - events: [ "postsync" ]
        command: bash
        args:
          - -c
          - |
            if [ "${GATEWAY}" = "gke-l7-regional-external-managed" ]; then
              echo "Removing timeout in HTTPRoute as GKE Gateway doesn't support it..."
              kubectl patch httproute ms-pd-llm-d-modelservice \
                -n ${NAMESPACE} \
                --type=json \
                -p='[{"op": "remove", "path": "/spec/rules/0/timeouts"}]' || echo "No timeouts found to remove"
            fi
