repositories:
  - name: llm-d-modelservice
    url: https://llm-d-incubation.github.io/llm-d-modelservice/

releases:
  - name: infra-pd
    namespace: llm-d-pd
    chart: oci://ghcr.io/llm-d-incubation/llm-d-infra/llm-d-infra
    version: 1.0.7
    installed: true
    labels:
      managedBy: llm-d-infra-installer

  - name: gaie-pd
    namespace: llm-d-pd
    chart: oci://registry.k8s.io/gateway-api-inference-extension/charts/inferencepool
    version: v0.5.1
    installed: true
    needs:
      - llm-d-pd/infra-pd
    values:
      - gaie-pd/values.yaml
    labels:
      managedBy: helmfile

  - name: ms-pd
    namespace: llm-d-pd
    chart: llm-d-modelservice/llm-d-modelservice
    version: 0.0.19
    installed: true
    needs:
      - llm-d-pd/infra-pd
      - llm-d-pd/gaie-pd
    values:
      - ms-pd/values.yaml
    labels:
      managedBy: helmfile
    hooks:
      - events: [ "postsync" ]
        command: bash
        args:
          - -c
          - |
            echo "Creating the destinationRule"
            kubectl create -f destinationRule.yaml -n llm-d-pd --dry-run=client -o yaml | kubectl apply -f -
      - events: [ "postsync" ]
        command: bash
        args:
          - -c
          - |
            echo "Patching HTTPRoute to trigger reconciliation..."
            kubectl patch httproute ms-pd-llm-d-modelservice \
              -n llm-d-pd \
              -p '{"metadata":{"labels":{"inferencepool":"ms-pd-llm-d-modelservice"}}}' \
              --type=merge
