apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This namespace must match the Subject namespaces for the RBAC in ./instance-w-prom-ds/rbac.yaml
namespace: llm-d-observability

resources:
- sa-token-secret.yaml
- grafana-instance.yaml
- rbac.yaml
- route.yaml
- datasource.yaml
