---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-sa-token
  annotations:
    kubernetes.io/service-account.name: grafana-sa-token
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-sa-token
